inventory_management_system/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('',views.index, name='index'),
    path('admin/addcategory/', views.add_category, name='addcategory'),
    path('admin/addsupplier/', views.add_supplier, name='addsupplier'),
    path('admin/addcustomer/', views.add_customer, name='addcustomer'),
    path('admin/addproduct/', views.add_product, name='addproduct'),
    path('purchase/addpurchase/', views.add_purchase, name='addpurchase'),
    path('purchase/addsale/', views.add_sale, name='addsale'),
    path('product/productlist/', views.productlist, name='productlist'),
    path('product/productdetails/<int:pk>', views.productdetails, name='productdetails'),
    path('product/deleteproduct/<int:pk>', views.delete_product, name='deleteproduct'),
    path('product/editproduct/<int:pk>', views.edit_product, name='editproduct'),


    path('category/categorylist/', views.category_list, name='categorylist'),
    path('category/categorydetails/<int:pk>', views.category_details, name='categorydetails'),
    path('category/deletecategory/<int:pk>', views.delete_category, name='deletecategory'),
    path('category/editcategory/<int:pk>', views.edit_category, name='editcategory'),

# -----------------sale urls ---------------------------------
    path('sale/salelist/', views.sale_list, name='salelist'),
    path('sale/saledetails/<int:pk>', views.sale_details, name='saledetails'),
    path('sale/deletesale/<int:pk>', views.delete_sale, name='deletesale'),
    path('sale/editsale/<int:pk>', views.edit_sale, name='editsale'),


# -----------------purchase urls ---------------------------------
    path('purchase/purchaselist/', views.purchase_list, name='purchaselist'),
    path('purchase/purchasedetails/<int:pk>', views.purchase_details, name='purchasedetails'),
    path('purchase/deletepurchase/<int:pk>', views.delete_purchase, name='deletepurchase'),

# -----------------customer urls ---------------------------------
    path('customer/customerlist/', views.customer_list, name='customerlist'),
    path('customer/customerdetails/<int:pk>', views.customer_details, name='customerdetails'),
    path('customer/deletecustomer/<int:pk>', views.delete_customer, name='deletecustomer'),
# -----------------customer urls ---------------------------------
    path('supplier/supplierlist/', views.supplier_list, name='supplierlist'),
    path('supplier/supplierdetails/<int:pk>', views.supplier_details, name='supplierdetails'),
    path('supplier/deletesupplier/<int:pk>', views.delete_supplier, name='deletesupplier'),






]

inventory_management_system/inventory_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/',include('dashboard.urls')),
    path('register/',user_views.register,name="register"),
    path('', auth_views.LoginView.as_view(template_name='user/log/login.html'), name='login'),
    path('logout/', user_views.logout_user, name='logout'),
    path('profile/',user_views.profile_update,name="profile"),
    path('users/userslist',user_views.user_list,name="userlist"),
    path('users/adduser',user_views.add_user,name="adduser"),
    path('users/deleteuser/<int:pk>',user_views.delete_user,name="deleteuser"),
    path('users/edit/<int:pk>',user_views.edit_user,name="edituser"),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT )


inventory_management_system/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string
import datetime
from django.db.models import Sum

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)

    def __str__(self):
        return self.name
    

class Customer(models.Model):
    name = models.CharField(max_length=100,null=True)
    email = models.EmailField(null=True) 
    phone = models.CharField(max_length=20,null=True)
    address = models.CharField(max_length=100,null=True)
    description = models.TextField(null=True)

    def __str__(self):
        return self.name
    

class Supplier(models.Model):
    name = models.CharField(max_length=100,null=True)
    email = models.EmailField(null=True) 
    phone = models.CharField(max_length=20,null=True)
    address = models.CharField(max_length=100,null=True)
    description = models.TextField(null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100,null=True)
    description = models.TextField(null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE,null=True)
    min_quantity = models.PositiveIntegerField(null=True)
    max_quantity = models.PositiveBigIntegerField(null=True)
    def __str__(self):
        return self.name

class Stock(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(null=True)
    date_updated = models.DateField(auto_now=True, null=True)

    def __str__(self):
        return f'{self.product} - {self.quantity}'




received_status = [('received','received'),('pending', 'pending')]

class PurchaseOrder(models.Model):
    order_number = models.CharField(unique=True,max_length=100, null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True)
    staff = models.ForeignKey(User,on_delete= models.SET_NULL, null=True)
    order_date = models.DateField(default=datetime.date.today,null=True)
    status = models.CharField(max_length=100, null=True,choices=received_status)
    total_order_cost = models.DecimalField(max_digits=10, decimal_places=2,null=True, editable=False)
    def save(self, *args, **kwargs):
        if not self.order_number:
            self.order_number = get_random_string(length=10)  # Generate a random string as the order number
        
        self.total_order_cost = PurchaseOrderItem.objects.filter(purchase_order=self).aggregate(Sum('total_price'))['total_price__sum'] or 0
        super().save(*args, **kwargs)
        

    def __str__(self):
        return f'{self.supplier} - {self.total_order_cost}'

class PurchaseOrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    purchase_order = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(null=True)
    # unit_price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, editable=False)

    def __str__(self):
        return f'{self.product} - {self.total_price}'
    
    def save(self, *args, **kwargs):
        # calculate total_price 
        self.total_price = self.product.price*self.quantity 
        super().save(*args, **kwargs)








payment_status = [('paid','paid'),('unpaid', 'unpaid')]
class Sale(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, null=True)
    sale_number = models.CharField(unique=True,max_length=100, null=True)
    staff = models.ForeignKey(User,on_delete= models.SET_NULL, null=True)
    sale_date = models.DateField(default=datetime.date.today, null=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, editable=False)
    payment_status = models.CharField(max_length=100, null=True,choices=payment_status)

    def save(self, *args, **kwargs):
        if not self.sale_number:
            self.sale_number = get_random_string(length=10)  # Generate a random string as the sale number

        # calculate total_amount based on related SaleItem objects
        self.total_amount = SaleItem.objects.filter(sale=self).aggregate(Sum('total_price'))['total_price__sum'] or 0
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.customer} - {self.total_amount}'
    



class SaleItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField( null=True)
    # unit_price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, editable=False)

    def __str__(self):
        return f'{self.product} - {self.total_price}'

    def save(self, *args, **kwargs):

        # calculate total_price 
        self.total_price = self.product.price*self.quantity 
        super().save(*args, **kwargs)

inventory_management_system/dashboard/forms.py
# forms.py
from django import forms
from .models import Category,Product,Supplier, Customer, PurchaseOrder, PurchaseOrderItem,Sale, SaleItem, Stock


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']

class CreateProductForm(forms.ModelForm):
    quantity = forms.IntegerField(widget=forms.TextInput()) 
    class Meta:
        model = Product
        fields = '__all__'
        widgets  = {
            'category' : forms.Select(attrs={'class': 'select'}),
            'supplier' : forms.Select(attrs={'class': 'select'}),
            'price' : forms.TextInput(),
            'min_quantity' : forms.TextInput(),
            'max_quantity' : forms.TextInput(),
        }
    def save(self, commit=True):
        product = super().save(commit=False)
        quantity = self.cleaned_data['quantity']
        
        if commit:
            product.save()
            stock = Stock.objects.create(product=product,quantity=quantity)
            stock.save()
        return product
class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets  = {
            'category' : forms.Select(attrs={'class': 'select'}),
            'supplier' : forms.Select(attrs={'class': 'select'}),
            'price' : forms.TextInput(),
            'min_quantity' : forms.TextInput(),
            'max_quantity' : forms.TextInput(),
        }
class StockForm(forms.ModelForm):
    class Meta: 
        model= Stock
        fields = ['quantity']
        widgets  = {
            'quantity' : forms.TextInput(),
        }

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = '__all__'

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'




class PurchaseOrderForm(forms.ModelForm):
    class Meta:
        model = PurchaseOrder
        fields = ['supplier', 'staff', 'order_date','status']


class PurchaseOrderItemForm(forms.ModelForm):
    class Meta:
        model = PurchaseOrderItem
        fields = ['product', 'quantity']


class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = '__all__'
        widgets  = {
            'customer' : forms.Select(attrs={'class': 'select'}),
            'staff' : forms.Select(attrs={'class': 'select'}),
            'payment_status' : forms.Select(attrs={'class': 'select'}),
        }

class SaleItemForm(forms.ModelForm):
    class Meta:
        model = SaleItem
        fields = ['product', 'quantity']
        widgets  = {
            'product' : forms.Select(attrs={'class': 'select'}),
            'quantity' : forms.TextInput(),
        }
    

inventory_management_system/templates/dashboard/staff/addsale.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}Add Sale{% endblock title %}

{% block content %}
<div class="content">
    <div class="page-header">
    <div class="page-title">
    <h4>Add Sale</h4>
    </div>
    </div>
    <div class="card">
    <div class="card-body">

    {% if not customer %}


    <form method="get">
    {% csrf_token %}
    <div class="row">
    <div class="col-lg-3 col-sm-6 col-12">
    <div class="form-group">
    <label>customer Name</label>
    <div class="row">
    <div class="col-lg-10 col-sm-10 col-10">
    <select name="customer" class="select" required>
        {% for customer in customers %}
        <option value="{{ customer.id }}">{{ customer.name }}</option>
        {% endfor %}
    </select>
    </div>
    </div>
    </div>
    </div>

    <div class="col-lg-3 col-sm-6 col-12">
        <div class="form-group">
        <label>Status</label>
        <div class="row">
        <div class="col-lg-10 col-sm-10 col-10">
        <select name="status" class="select" required>
            <option value="paid">Paid</option>
            <option value="unpaid">Unpaid</option>
        </select>
        </div>
        </div>
        </div>
    </div>
    
    <div class="col-lg-3 col-sm-6 col-12">
        <div class="form-group">
        <label>Sale Date </label>
        <div class="input-groupicon">
         
        <input type="text" type="date" placeholder="YYYY-MM-DD" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}" name ="date" required>
                
        <div class="addonset">
        <img src="{% static 'img/icons/calendars.svg' %}" alt="img">
        </div>
        </div>
        </div>
        
    </div>
    <div class="col-lg-12">
        <button class="btn btn-submit me-2" type="submit">Select</button>
        </div>
    </form>
    
    </div>

    {% else %}
    

    <form method="post" class="form-check">
    {% csrf_token %}
    <div class="row">
        <div class="col-lg-3 col-sm-6 col-12">
            <div class="form-group">
            <label>Customer Name</label>
            <input type="text" name="customer" value="{{ customer.name }}" readonly>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 col-12">
            <div class="form-group">
            <label>Status</label>
            <input type="text" name="status" value="{{ status }}" readonly>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 col-12">
            <div class="form-group">
            <label>Date</label>
            <input type="text" name="date" value="{{ date }}" readonly>
            </div>
        </div>
    </div>    
       

    <div class="row">
    <div class="table-responsive">
    <table class="table">
    <thead>
    <tr>
    <th>Product Name</th>
    <th>QTY</th>
    <th class="text-end">Unit Price($)</th>
    </tr>
    </thead>
    <tbody>
        {% for product in products %}
    <tr>
    <td >
    <input type="checkbox" name="id_{{ product.id }}" >
    <a href="javascript:void(0);" name="">{{product.name}}</a>
    </td>
    <td><input type="number" name="quantity_{{ product.id }}" value="1" min="1"></td>
    <td class="text-end">{{ product.price }}</td>

    </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-sm-6 col-12">
        <div class="col-lg-12">
            <button class="btn btn-submit me-2" type="submit">submit</button>
            <a href="{% url 'dashboard:addsale' %}" class="btn btn-cancel">Cancel</a>
        </div>
        </div>
    </div>

</form>
{% endif %}
</div>
</div>
{% endblock content %}

inventory_management_system/templates/dashboard/staff/categorylist.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}Category List{% endblock title %}


{% block content %}
<div class="content">
    <div class="page-header">
    <div class="page-title">
    <h4>Category List</h4>
    <h6>Manage your categories</h6>
    </div>
    <div class="page-btn">
    <a href="{% url 'dashboard:addcategory' %}" class="btn btn-added"><img src="{% static 'img/icons/plus.svg' %}" alt="img" class="me-1">Add New category</a>
    </div> 
    </div>
    
    <div class="card">
    <div class="card-body">
    <div class="table-top">
    <div class="search-set">
    <div class="search-input">
    <a class="btn btn-searchset"><img src="{% static 'img/icons/search-white.svg' %}" alt="img"></a>
    </div>
    </div>
   
    </div>
    
    
    
    <div class="table-responsive">
    <table class="table  datanew">
    <thead>
    <tr>
    <th>Category Name</th>

    <th>Description</th>
    <th></th>
    </tr>
    </thead>
    <tbody>
        
        {% for category in categories %}
        <tr>
            <td>{{category.name}}</td>

            <td>{{category.description}}</td>
            <td>
                <a class="me-3" href="{% url 'dashboard:categorydetails' category.id %}">
                <img src="{% static 'img/icons/eye.svg' %}" alt="img">
                </a>
                <a class="me-3" href="{% url 'dashboard:editcategory' category.id %}">
                <img src="{% static 'img/icons/edit.svg' %}" alt="img">
                </a>
                <a href="{% url 'dashboard:deletecategory' category.id %}">
                <img src="{% static 'img/icons/delete.svg' %}" alt="img">
                </a>
            </td>
            
        </tr>
        {% endfor %}
    </tbody> 
    </table>
    </div>
    </div>
    </div>
    
    </div>
    
{% endblock content %}

inventory_management_system/templates/dashboard/staff/index_buyer.html
{% extends 'partials/base.html' %}
{% block title %}Welcome to Buyer Dashboard{% endblock title %}


{% block content %}
<div class="content">
    <div class="row">


        <div class="col-lg-3 col-sm-6 col-12 d-flex">
        <div class="dash-count">
        <div class="dash-counts">
        <h4>{{suppliers}}</h4>
        <h5>Suppliers</h5>
        </div>
        <div class="dash-imgs">
        <i data-feather="user"></i>
        </div>
        </div>
        </div>
        
       
        <div class="col-lg-3 col-sm-6 col-12 d-flex">
        <div class="dash-count das3">
        <div class="dash-counts">
        <h4>{{purchases_received}}</h4>
        <h5>Purchases Received</h5>
        </div>
        <div class="dash-imgs">
        <i data-feather="file"></i>
        </div>
        </div>
        </div>
        <div class="col-lg-3 col-sm-6 col-12 d-flex">
            <div class="dash-count das2">
            <div class="dash-counts">
            <h4>{{purchases_pending}}</h4>
            <h5>Purchases Pending</h5>
            </div>
            <div class="dash-imgs">
            <i data-feather="file-text"></i>
            </div>
            </div>
            </div>
        
    </div>

    <div class="row">
        <div class="col-lg-7 col-sm-12 col-12 d-flex">
            <div class="card flex-fill">
                
                <div class="card-header pb-0 d-flex justify-content-between align-items-center">
                    <h5 class="card-title mb-0">Purchases</h5>
                    
                        <div class="graph-sets">
                            {% if years  %}
                            <form  method="post">
                                {% csrf_token %} 
                            <select name="year" class="select"  onchange="this.form.submit()">
                                <option value="" >year</option>
                                {% for year in years %}
                                  <option value="{{ year|date:'Y' }}" >{{ year|date:'Y' }}</option>
                                {% endfor %}
                            </select> 
                            {% endif %}
                        </div>
                    </form>
                </div>
                <div class="card-body">
                    {% if purchases  %}
                    <canvas id="purchases"></canvas>
                    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
                    <script>
                        const purchases = [
                            {% for purchase in purchases %}
                            {'month': '{{ purchase.month|date:'F' }}', 'purchases' : {{ purchase.total_order_cost }} },
                            {% endfor %}
                        ];
                        const data2 = {
                            datasets : [{
                                label: 'Purchases per Month',
                                data: purchases,
                                backgroundColor:'rgba(75,192,192,0.2)',
                                borderColor:'rgba(75,192,192,1)',
                                tension: 0.4,
                                parsing : {
                                    xAxisKey:'month',
                                    yAxisKey:'purchases'
                                }
                            }]
                        }
                        const config1 ={
                            type: 'line',
                            data: data2 ,
                            options: {
                            scales: {
                                y: {
                                beginAtZero: true
                                }
                            }
                            
                            }
                        }
                       
                        const mychart1 = new Chart(document.getElementById('purchases'), config1 );
                    </script>
                    {% endif %}
                </div>
                
                
            </div>
        </div>
        
    </div>
</div>
{% endblock content %}

<div class="col-lg-5 col-sm-12 col-12 d-flex">
    <div class="card flex-fill">
    <div class="card-header pb-0 d-flex justify-content-between align-items-center">
    <h4 class="card-title mb-0">Recently Added Products</h4>
    <div class="dropdown">
    <a href="javascript:void(0);" data-bs-toggle="dropdown" aria-expanded="false" class="dropset">
    <i class="fa fa-ellipsis-v"></i>
    </a>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <li>
    <a href="{% url 'dashboard:productlist' %}" class="dropdown-item">Product List</a>
    </li>
    <li>
    <a href="{% url 'dashboard:addproduct' %}" class="dropdown-item">Product Add</a>
    </li>
    </ul>
    </div>
    </div>
    <div class="card-body">
    <div class="table-responsive dataview">
    <table class="table datatable ">
    <thead>
    <tr>
    <th>Id</th>
    <th>Products</th>
    <th>Price</th>
    </tr>
    </thead>
    <tbody>
        {% for product in products %}
    <tr>
    <td>{{product.id}}</td>
    <td >
    {{product.name}}
    </td>
    <td>{{product.price}}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
    </div>
    </div>
</div>

inventory_management_system/templates/dashboard/staff/index_vendor.html
{% extends 'partials/base.html' %}
{% block title %}Welcome to Vendor Dashboard{% endblock title %}


{% block content %}
<div class="content">
    <div class="row">


        <div class="col-lg-3 col-sm-6 col-12 d-flex">
        <div class="dash-count">
        <div class="dash-counts">
        <h4>{{customers}}</h4>
        <h5>Customers</h5>
        </div>
        <div class="dash-imgs">
        <i data-feather="user"></i>
        </div>
        </div>
        </div>
        
       
        <div class="col-lg-3 col-sm-6 col-12 d-flex">
        <div class="dash-count das3">
        <div class="dash-counts">
        <h4>{{sales_paid}}</h4>
        <h5>Sales Paid</h5>
        </div>
        <div class="dash-imgs">
        <i data-feather="file"></i>
        </div>
        </div>
        </div>
        <div class="col-lg-3 col-sm-6 col-12 d-flex">
            <div class="dash-count das2">
            <div class="dash-counts">
            <h4>{{sales_unpaid}}</h4>
            <h5>Sales Unpaid</h5>
            </div>
            <div class="dash-imgs">
            <i data-feather="file-text"></i>
            </div>
            </div>
            </div>
        
    </div>

    <div class="row">
        <div class="col-lg-7 col-sm-12 col-12 d-flex">
            <div class="card flex-fill">
                
                <div class="card-header pb-0 d-flex justify-content-between align-items-center">
                    <h5 class="card-title mb-0">Sales</h5>
                    
                        <div class="graph-sets">
                            {% if years  %}
                            <form  method="post">
                                {% csrf_token %} 
                            <select name="year" class="select"  onchange="this.form.submit()">
                                <option value="" >year</option>
                                {% for year in years %}
                                  <option value="{{ year|date:'Y' }}" >{{ year|date:'Y' }}</option>
                                {% endfor %}
                            </select> 
                            {% endif %}
                        </div>
                    </form>
                </div>
                <div class="card-body">
                    {% if sales  %}
                    <canvas id="sales"></canvas>
                    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
                    <script>
                        const sales = [
                            {% for sale in sales %}
                            {'month': '{{ sale.month|date:'F' }}', 'sales' : {{ sale.total_amount}} },
                            {% endfor %}
                        ];
                        const data = {
                            datasets : [{
                                label: 'Sales per Month',
                                data: sales,
                                backgroundColor:'rgba(255,26,104,0.2)',
                                borderColor:'rgba(255,26,104,1)',
                                tension: 0.4,
                                parsing : {
                                    xAxisKey:'month',
                                    yAxisKey:'sales'
                                }
                            }]
                        }
                        const config ={
                            type: 'line',
                            data ,
                            options: {
                            scales: {
                                y: {
                                beginAtZero: true
                                }
                            }
                            
                            }
                        }
                        const ctx = document.getElementById('sales');
                        const mychart = new Chart(ctx,config );
                    </script>
                    {% endif %}
                </div>
                
                
            </div>
        </div>
        <div class="col-lg-5 col-sm-12 col-12 d-flex">
                <div class="card flex-fill">
                <div class="card-header pb-0 d-flex justify-content-between align-items-center">
                <h4 class="card-title mb-0">Recently Added Products</h4>
                <div class="dropdown">
                <a href="javascript:void(0);" data-bs-toggle="dropdown" aria-expanded="false" class="dropset">
                <i class="fa fa-ellipsis-v"></i>
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li>
                <a href="{% url 'dashboard:productlist' %}" class="dropdown-item">Product List</a>
                </li>
                <li>
                <a href="{% url 'dashboard:addproduct' %}" class="dropdown-item">Product Add</a>
                </li>
                </ul>
                </div>
                </div>
                <div class="card-body">
                <div class="table-responsive dataview">
                <table class="table datatable ">
                <thead>
                <tr>
                <th>Id</th>
                <th>Products</th>
                <th>Price</th>
                </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                <tr>
                <td>{{product.id}}</td>
                <td >
                {{product.name}}
                </td>
                <td>{{product.price}}</td>
                </tr>
                {% endfor %}
                </tbody>
                </table>
                </div>
                </div>
                </div>
        </div>
    </div>
</div>
{% endblock content %}

inventory_management_system/templates/dashboard/staff/productlist.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}Product List{% endblock title %}


{% block content %}
<div class="content">
    <div class="page-header">
    <div class="page-title">
    <h4>Product List</h4>
    <h6>Manage your products</h6>
    </div>
    <div class="page-btn">
    <a href="{% url 'dashboard:addproduct' %}" class="btn btn-added"><img src="{% static 'img/icons/plus.svg' %}" alt="img" class="me-1">Add New Product</a>
    </div>
    </div>
    
    <div class="card">
    <div class="card-body">
    <div class="table-top">
    <div class="search-set">
    <div class="search-input">
    <a class="btn btn-searchset"><img src="{% static 'img/icons/search-white.svg' %}" alt="img"></a>
    </div>
    </div>
   
    </div>
    
    
    
    <div class="table-responsive">
    <table class="table  datanew">
    <thead>
    <tr>
    <th>Product Name</th>
    <th>Category </th>
    <th>price</th>
    <th>Qty</th>
    <th>Action</th>
    </tr>
    </thead>
    <tbody>
        {% for product in products %}
        
        <tr>
            <td>{{product.name}}</td>
            <td>{{product.category}}</td>
            <td>{{product.price}}</td>
            <td>{{product.stock.quantity}}</td>
            <td>
            <a class="me-3" href="{% url 'dashboard:productdetails' product.id %}">
            <img src="{% static 'img/icons/eye.svg' %}" alt="img">
            </a>
            <a class="me-3" href="{% url 'dashboard:editproduct' product.id %}">
            <img src="{% static 'img/icons/edit.svg' %}" alt="img">
            </a>
            <a href="{% url 'dashboard:deleteproduct' product.id %}">
            <img src="{% static 'img/icons/delete.svg' %}" alt="img">
            </a>
            </td>
        </tr>

        {% endfor %}
    </tbody>
    </table>
    </div>
    </div>
    </div>
    
    </div>
{% endblock content %}