inventory_management_system/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('',views.index, name='index'),
    path('admin/addcategory/', views.add_category, name='addcategory'),
    path('admin/addsupplier/', views.add_supplier, name='addsupplier'),
    path('admin/addcustomer/', views.add_customer, name='addcustomer'),
    path('admin/addproduct/', views.add_product, name='addproduct'),
    path('purchase/addpurchase/', views.add_purchase, name='addpurchase'),
    path('purchase/addsale/', views.add_sale, name='addsale'),
    path('product/productlist/', views.productlist, name='productlist'),
    path('product/productdetails/<int:pk>', views.productdetails, name='productdetails'),
    path('product/deleteproduct/<int:pk>', views.delete_product, name='deleteproduct'),
    path('product/editproduct/<int:pk>', views.edit_product, name='editproduct'),


    path('category/categorylist/', views.category_list, name='categorylist'),
    path('category/categorydetails/<int:pk>', views.category_details, name='categorydetails'),
    path('category/deletecategory/<int:pk>', views.delete_category, name='deletecategory'),
    path('category/editcategory/<int:pk>', views.edit_category, name='editcategory'),

# -----------------sale urls ---------------------------------
    path('sale/salelist/', views.sale_list, name='salelist'),
    path('sale/saledetails/<int:pk>', views.sale_details, name='saledetails'),
    path('sale/deletesale/<int:pk>', views.delete_sale, name='deletesale'),
    path('sale/editsale/<int:pk>', views.edit_sale, name='editsale'),


# -----------------purchase urls ---------------------------------
    path('purchase/purchaselist/', views.purchase_list, name='purchaselist'),
    path('purchase/purchasedetails/<int:pk>', views.purchase_details, name='purchasedetails'),
    path('purchase/deletepurchase/<int:pk>', views.delete_purchase, name='deletepurchase'),

# -----------------customer urls ---------------------------------
    path('customer/customerlist/', views.customer_list, name='customerlist'),
    path('customer/customerdetails/<int:pk>', views.customer_details, name='customerdetails'),
    path('customer/deletecustomer/<int:pk>', views.delete_customer, name='deletecustomer'),
# -----------------customer urls ---------------------------------
    path('supplier/supplierlist/', views.supplier_list, name='supplierlist'),
    path('supplier/supplierdetails/<int:pk>', views.supplier_details, name='supplierdetails'),
    path('supplier/deletesupplier/<int:pk>', views.delete_supplier, name='deletesupplier'),






]

inventory_management_system/inventory_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/',include('dashboard.urls')),
    path('register/',user_views.register,name="register"),
    path('', auth_views.LoginView.as_view(template_name='user/log/login.html'), name='login'),
    path('logout/', user_views.logout_user, name='logout'),
    path('profile/',user_views.profile_update,name="profile"),
    path('users/userslist',user_views.user_list,name="userlist"),
    path('users/adduser',user_views.add_user,name="adduser"),
    path('users/deleteuser/<int:pk>',user_views.delete_user,name="deleteuser"),
    path('users/edit/<int:pk>',user_views.edit_user,name="edituser"),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT )


inventory_management_system/dashboard/forms.py
# forms.py
from django import forms
from .models import Category,Product,Supplier, Customer, PurchaseOrder, PurchaseOrderItem,Sale, SaleItem, Stock


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']

class CreateProductForm(forms.ModelForm):
    quantity = forms.IntegerField(widget=forms.TextInput()) 
    class Meta:
        model = Product
        fields = '__all__'
        widgets  = {
            'category' : forms.Select(attrs={'class': 'select'}),
            'supplier' : forms.Select(attrs={'class': 'select'}),
            'price' : forms.TextInput(),
            'min_quantity' : forms.TextInput(),
            'max_quantity' : forms.TextInput(),
        }
    def save(self, commit=True):
        product = super().save(commit=False)
        quantity = self.cleaned_data['quantity']
        
        if commit:
            product.save()
            stock = Stock.objects.create(product=product,quantity=quantity)
            stock.save()
        return product
class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets  = {
            'category' : forms.Select(attrs={'class': 'select'}),
            'supplier' : forms.Select(attrs={'class': 'select'}),
            'price' : forms.TextInput(),
            'min_quantity' : forms.TextInput(),
            'max_quantity' : forms.TextInput(),
        }
class StockForm(forms.ModelForm):
    class Meta: 
        model= Stock
        fields = ['quantity']
        widgets  = {
            'quantity' : forms.TextInput(),
        }

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = '__all__'

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'




class PurchaseOrderForm(forms.ModelForm):
    class Meta:
        model = PurchaseOrder
        fields = ['supplier', 'staff', 'order_date','status']


class PurchaseOrderItemForm(forms.ModelForm):
    class Meta:
        model = PurchaseOrderItem
        fields = ['product', 'quantity']


class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = '__all__'
        widgets  = {
            'customer' : forms.Select(attrs={'class': 'select'}),
            'staff' : forms.Select(attrs={'class': 'select'}),
            'payment_status' : forms.Select(attrs={'class': 'select'}),
        }

class SaleItemForm(forms.ModelForm):
    class Meta:
        model = SaleItem
        fields = ['product', 'quantity']
        widgets  = {
            'product' : forms.Select(attrs={'class': 'select'}),
            'quantity' : forms.TextInput(),
        }
    

inventory_management_system/dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.forms import modelformset_factory
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import CategoryForm, CreateProductForm,EditProductForm, StockForm ,SupplierForm, CustomerForm, PurchaseOrderForm, PurchaseOrderItemForm, SaleForm, SaleItemForm
from .models import Product, Supplier, PurchaseOrder, PurchaseOrderItem, Customer, Sale, SaleItem, Category, Stock
from django.db.models import Sum, Count
from django.db.models.functions import ExtractMonth,ExtractYear
from django.db.models.functions import TruncMonth, TruncYear
from django.http import JsonResponse
from datetime import datetime
# Create your views here.


@login_required
def index(request):
    if request.user.is_superuser :
        return index_admin(request)
    elif request.user.groups.filter(name='vendors').exists() :
        return index_vendor(request)
    elif  request.user.groups.filter(name='buyers').exists() :
        return index_buyer(request)

@login_required
@user_passes_test(lambda u:  u.is_superuser, login_url='login')
def index_admin(request):
    products = Product.objects.order_by('-id')[:5]
    suppliers = Supplier.objects.all().count()
    customers = Customer.objects.all().count()
    total_purchases = PurchaseOrder.objects.aggregate(Sum('total_order_cost'))['total_order_cost__sum'] or 0
    total_sales = Sale.objects.aggregate(Sum('total_amount'))['total_amount__sum'] or 0
    purchases_received = PurchaseOrder.objects.filter(status = 'received').count()
    purchases_pending = PurchaseOrder.objects.filter(status = 'pending').count()
    sales_paid = Sale.objects.filter(payment_status = 'paid').count()
    sales_unpaid = Sale.objects.filter(payment_status = 'unpaid').count()
    years = Sale.objects.dates('sale_date', 'year')


    if request.method == 'POST':
        selected_year = request.POST.get('year')
        sales = Sale.objects.filter(sale_date__year=selected_year).annotate(
            year=TruncYear('sale_date'),
            month=TruncMonth('sale_date')
        ).values('year', 'month').annotate(
            total_amount=Sum('total_amount')
        ).order_by('year', 'month')
        purchases = PurchaseOrder.objects.filter(order_date__year=selected_year).annotate(
            year=TruncYear('order_date'),
            month=TruncMonth('order_date')
        ).values('year', 'month').annotate(
            total_order_cost=Sum('total_order_cost')
        ).order_by('year', 'month')
        context ={
        'suppliers' : suppliers,
        'customers': customers,
        'products' : products,
        'sales_paid':sales_paid,
        'purchases_received':purchases_received,
        'total_purchases' : total_purchases,
        'total_sales' : total_sales,
        'sales': sales,
        'purchases': purchases,
        'years' : years,
        } 

    else : 
        context ={
            'suppliers' : suppliers,
            'customers': customers,
            'products' : products,
            'sales_paid':sales_paid,
            'sales_unpaid':sales_unpaid,
            'purchases_received':purchases_received,
            'purchases_pending' : purchases_pending,
            'total_purchases' : total_purchases,
            'total_sales' : total_sales,
            'years' : years,
            
        } 
    return render(request,'dashboard/admin/index.html',context=context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='vendors').exists(), login_url='login')
def index_vendor(request):
    products = Product.objects.order_by('-id')[:5]
    customers = Customer.objects.all().count()
    sales_paid = Sale.objects.filter(payment_status = 'paid').count()
    sales_unpaid = Sale.objects.filter(payment_status = 'unpaid').count()
    years = Sale.objects.dates('sale_date', 'year')

    if request.method == 'POST':
        selected_year = request.POST.get('year')
        sales = Sale.objects.filter(sale_date__year=selected_year).annotate(
            year=TruncYear('sale_date'),
            month=TruncMonth('sale_date')
        ).values('year', 'month').annotate(
            total_amount=Sum('total_amount')
        ).order_by('year', 'month')
        context = {
        'customers' : customers,
        'sales_paid' : sales_paid,
        'sales_unpaid' : sales_unpaid,
        'sales' : sales,
        'years' : years,
        'products' :products}
        return render(request,'dashboard/staff/index_vendor.html', context=context)
    else :
        context = {
            'customers' : customers,
            'sales_paid' : sales_paid,
            'sales_unpaid' : sales_unpaid,
            'years' : years,
            'products':products,
        }
    return render(request,'dashboard/staff/index_vendor.html', context=context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='buyers').exists(), login_url='login')
def index_buyer(request):
    products = Product.objects.order_by('-id')[:5]
    suppliers = Supplier.objects.all().count()
    purchases_received = PurchaseOrder.objects.filter(status = 'received').count()
    purchases_pending = PurchaseOrder.objects.filter(status = 'pending').count()
    years = Sale.objects.dates('sale_date', 'year')

    if request.method == 'POST':
        selected_year = request.POST.get('year')
        purchases = PurchaseOrder.objects.filter(order_date__year=selected_year).annotate(
            year=TruncYear('order_date'),
            month=TruncMonth('order_date')
        ).values('year', 'month').annotate(
            total_order_cost=Sum('total_order_cost')
        ).order_by('year', 'month')
        context = {
        'suppliers' : suppliers,
        'purchases_received' : purchases_received,
        'purchases_pending' : purchases_pending,
        'purchases' : purchases,
        'years' : years,
        'products' :products}
        return render(request,'dashboard/staff/index_buyer.html', context=context)
    else :
        context = {
            'suppliers' : suppliers,
            'purchases_received' : purchases_received,
            'purchases_pending' : purchases_pending,
            'years' : years,
            'products':products,
        }
    return render(request,'dashboard/staff/index_buyer.html', context=context)

#--------------------category views----------------------------------------------------------

@login_required
@user_passes_test(lambda u: u.groups.filter(name='buyers').exists() or u.is_superuser, login_url='login')
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard:categorylist')  
    else:
        form = CategoryForm()
    return render(request, 'dashboard/admin/addcategory.html', {'form': form})


@login_required
@user_passes_test(lambda u: u.groups.filter(name='buyers').exists() or u.groups.filter(name='vendors').exists() or u.is_superuser, login_url='login')
def category_list(request):
    categories = Category.objects.all()
    context = {
        'categories' : categories,
    }
    return render(request,'dashboard/staff/categorylist.html',context= context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='buyers').exists() or u.groups.filter(name='vendors').exists() or u.is_superuser, login_url='login')
def category_details(request, pk):
    category = Category.objects.get(id=pk)
    context = {
        'category' : category,
    }
    return render(request,'dashboard/staff/categorydetails.html', context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='buyers').exists() or u.is_superuser, login_url='login')
def delete_category(request, pk):
    category = Category.objects.get(id=pk)
    if request.method == 'POST':
        category.delete()
        return redirect('dashboard:categorylist')
    return render(request, 'dashboard/staff/deletecategory.html')


@login_required
@user_passes_test(lambda u: u.groups.filter(name='buyers').exists() or u.is_superuser, login_url='login')
def edit_category(request, pk):
    category = Category.objects.get(id=pk)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('dashboard:categorylist')
        else : return
    else :
        form = EditProductForm(instance=category)
    context = {
        'form' : form,
    }

    return render(request,'dashboard/staff/editcategory.html', context)


#--------------------product views----------------------------------------------------------

@login_required
@user_passes_test(lambda u: u.groups.filter(name='buyers').exists() or u.is_superuser, login_url='login')
@login_required
def add_product(request):
    if request.method == 'POST':
        form = CreateProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard:productlist')  
    else:
        form = CreateProductForm()
    
    return render(request, 'dashboard/admin/addproduct.html', {'form': form})

@login_required
@user_passes_test(lambda u: u.groups.filter(name='buyers').exists() or u.groups.filter(name='vendors').exists() or u.is_superuser, login_url='login')
def productlist(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    context = {
        'products' : products,
        'categories' : categories,
    }
    return render(request,'dashboard/staff/productlist.html', context)

@login_required

inventory_management_system/templates/dashboard/people/customerdetails.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}Customer Details{% endblock title %}

{% block content %}

<div class="content">
    <div class="page-header">
    <div class="page-title">
    <h4>Customer Details</h4>
    <h6>Full details of a customer</h6>
    </div>
    </div>
    
    <div class="row" >
        <div class="col-lg-8 col-sm-12">
            <div class="card">
            <div class="card-body">
            <div class="productdetails">
            <ul class="product-bar">
            <li>
            <h4>customer Name</h4>
            <h6>{{customer.name}}</h6>
            </li>
            <li>
            <h4>Email</h4>
            <h6>{{customer.email}}</h6>
            </li>
            <li>
                <h4>phone</h4>
                <h6>{{customer.phone}}</h6>
            </li>
            <li>
                <h4>customer addres</h4>
                <h6>{{customer.address}}</h6>
                </li>
            <li>
                <h4>Description</h4>
                <h6>{{customer.description}}</h6>
            </li>
        
            </ul>
            </div>
            </div>
            </div>
            </div>
   
        


    <div class="row" >
        <div class="col-lg-12">
            <a href="{% url 'dashboard:customerlist' %}" class="btn btn-submit me-2">Back to list</a>
            </div>
        </div>
    
</div>
</div>

{% endblock content %}

inventory_management_system/templates/dashboard/people/customerlist.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}Customer List{% endblock title %}


{% block content %}
<div class="content">
    <div class="page-header">
    <div class="page-title">
    <h4>Customer List</h4>
    <h6>Manage your customers</h6>
    </div>
    <div class="page-btn">
    <a href="{% url 'dashboard:addcustomer' %}" class="btn btn-added"><img src="{% static 'img/icons/plus.svg' %}" alt="img" class="me-1">Add New customer</a>
    </div> 
    </div>
    
    <div class="card">
    <div class="card-body">
    <div class="table-top">
    <div class="search-set">
    <div class="search-input">
    <a class="btn btn-searchset"><img src="{% static 'img/icons/search-white.svg' %}" alt="img"></a>
    </div>
    </div>
   
    </div>
    
    
    
    <div class="table-responsive">
    <table class="table  datanew">
    <thead>
    <tr>
    <th>Customer</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Description</th>
    
    <th></th>
    </tr>
    </thead>
    <tbody>
        
        {% for customer in customers %}
        <tr>
            <td>{{customer.name}}</td>
            <td>{{customer.email}}</td>
            
            <td>{{customer.phone}}</td>
            <td>{{customer.address}}</td>
            <td>{{customer.description}}</td>
            <td>
                <a class="me-3" href="{% url 'dashboard:customerdetails' customer.id %}">
                <img src="{% static 'img/icons/eye.svg' %}" alt="img">
                </a>
            
                {% comment %} <a class="me-3" href="{% url 'dashboard:editcustomer' customer.id %}">
                <img src="{% static 'img/icons/edit.svg' %}" alt="img">
                </a> {% endcomment %}
                <a href="{% url 'dashboard:deletecustomer' customer.id %}">
                <img src="{% static 'img/icons/delete.svg' %}" alt="img"> 
                </a>
            </td>
            
        </tr>
        {% endfor %}
    </tbody> 
    </table>
    </div>
    </div>
    </div>
    
    </div>
    
{% endblock content %}

inventory_management_system/templates/dashboard/people/deletecustomer.html

{% extends 'partials/base.html' %}
{% load static %}
{% block title %}Delete Customer{% endblock title %}

{% block content %}

<div class="content">
    <div class="page-header">
    <div class="page-title">
    <h4>Delete Customer</h4>
    </div>
    </div>
    
    <div class="row" >
    <div class="col-lg-8 col-sm-12">
    <div class="card">
    <div class="card-body">
        <h3>Delete Customer</h3>
        <hr>
        <div class="alret alret-danger">
            <h4>Are you sure you want to delete?</h4>
        </div>
        <form method="post">
            {% csrf_token %}
            <a href="{% url 'dashboard:customerlist' %}" class="btn btn-cancel">Cancel</a>
            <input type="submit" class="btn btn-submit me-2" value="confirm">
        </form>
    </div>
    </div>
    </div>
    
    </div>
    
</div>


{% endblock content %}

inventory_management_system/templates/dashboard/people/deletesupplier.html

{% extends 'partials/base.html' %}
{% load static %}
{% block title %}Delete Supplier{% endblock title %}

{% block content %}

<div class="content">
    <div class="page-header">
    <div class="page-title">
    <h4>Delete Supplier</h4>
    </div>
    </div>
    
    <div class="row" >
    <div class="col-lg-8 col-sm-12">
    <div class="card">
    <div class="card-body">
        <h3>Delete Supplier</h3>
        <hr>
        <div class="alret alret-danger">
            <h4>Are you sure you want to delete?</h4>
        </div>
        <form method="post">
            {% csrf_token %}
            <a href="{% url 'dashboard:supplierlist' %}" class="btn btn-cancel">Cancel</a>
            <input type="submit" class="btn btn-submit me-2" value="confirm">
        </form>
    </div>
    </div>
    </div>
    
    </div>
    
</div>


{% endblock content %}

inventory_management_system/templates/dashboard/people/supplierdetails.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}Supplier Details{% endblock title %}

{% block content %}

<div class="content">
    <div class="page-header">
    <div class="page-title">
    <h4>Supplier Details</h4>
    <h6>Full details of a supplier</h6>
    </div>
    </div>
    
    <div class="row" >
        <div class="col-lg-8 col-sm-12">
            <div class="card">
            <div class="card-body">
            <div class="productdetails">
            <ul class="product-bar">
            <li>
            <h4>supplier Name</h4>
            <h6>{{supplier.name}}</h6>
            </li>
            <li>
            <h4>Email</h4>
            <h6>{{supplier.email}}</h6>
            </li>
            <li>
                <h4>phone</h4>
                <h6>{{supplier.phone}}</h6>
            </li>
            <li>
                <h4>supplier addres</h4>
                <h6>{{supplier.address}}</h6>
                </li>
            <li>
                <h4>Description</h4>
                <h6>{{supplier.description}}</h6>
            </li>
        
            </ul>
            </div>
            </div>
            </div>
            </div>
   
      


    <div class="row" >
        <div class="col-lg-12">
            <a href="{% url 'dashboard:supplierlist' %}" class="btn btn-submit me-2">Back to list</a>
            </div>
        </div>
    
</div>
</div>

{% endblock content %}

inventory_management_system/templates/dashboard/people/supplierlist.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}Supplier List{% endblock title %}


{% block content %}
<div class="content">
    <div class="page-header">
    <div class="page-title">
    <h4>Supplier List</h4>
    <h6>Manage your suppliers</h6>
    </div>
    <div class="page-btn">
    <a href="{% url 'dashboard:addsupplier' %}" class="btn btn-added"><img src="{% static 'img/icons/plus.svg' %}" alt="img" class="me-1">Add New supplier</a>
    </div> 
    </div>
    
    <div class="card">
    <div class="card-body">
    <div class="table-top">
    <div class="search-set">
    <div class="search-input">
    <a class="btn btn-searchset"><img src="{% static 'img/icons/search-white.svg' %}" alt="img"></a>
    </div>
    </div>
   
    </div>
    
    
    
    <div class="table-responsive">
    <table class="table  datanew">
    <thead>
    <tr>
    <th>supplier</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Description</th>
    
    <th></th>
    </tr>
    </thead>
    <tbody>
        
        {% for supplier in suppliers %}
        <tr>
            <td>{{supplier.name}}</td>
            <td>{{supplier.email}}</td>
            
            <td>{{supplier.phone}}</td>
            <td>{{supplier.address}}</td>
            <td>{{supplier.description}}</td>
            <td>
                <a class="me-3" href="{% url 'dashboard:supplierdetails' supplier.id %}">
                <img src="{% static 'img/icons/eye.svg' %}" alt="img">
                </a>
            
                {% comment %} <a class="me-3" href="{% url 'dashboard:editsupplier' supplier.id %}">
                <img src="{% static 'img/icons/edit.svg' %}" alt="img">
                </a> {% endcomment %}
                <a href="{% url 'dashboard:deletesupplier' supplier.id %}">
                <img src="{% static 'img/icons/delete.svg' %}" alt="img"> 
                </a>
            </td>
            
        </tr>
        {% endfor %}
    </tbody> 
    </table>
    </div>
    </div>
    </div>
    
    </div>
    
{% endblock content %}