inventory_management_system/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('',views.index, name='index'),
    path('admin/addcategory/', views.add_category, name='addcategory'),
    path('admin/addsupplier/', views.add_supplier, name='addsupplier'),
    path('admin/addcustomer/', views.add_customer, name='addcustomer'),
    path('admin/addproduct/', views.add_product, name='addproduct'),
    path('purchase/addpurchase/', views.add_purchase, name='addpurchase'),
    path('purchase/addsale/', views.add_sale, name='addsale'),
    path('product/productlist/', views.productlist, name='productlist'),
    path('product/productdetails/<int:pk>', views.productdetails, name='productdetails'),
    path('product/deleteproduct/<int:pk>', views.delete_product, name='deleteproduct'),
    path('product/editproduct/<int:pk>', views.edit_product, name='editproduct'),


    path('category/categorylist/', views.category_list, name='categorylist'),
    path('category/categorydetails/<int:pk>', views.category_details, name='categorydetails'),
    path('category/deletecategory/<int:pk>', views.delete_category, name='deletecategory'),
    path('category/editcategory/<int:pk>', views.edit_category, name='editcategory'),

# -----------------sale urls ---------------------------------
    path('sale/salelist/', views.sale_list, name='salelist'),
    path('sale/saledetails/<int:pk>', views.sale_details, name='saledetails'),
    path('sale/deletesale/<int:pk>', views.delete_sale, name='deletesale'),
    path('sale/editsale/<int:pk>', views.edit_sale, name='editsale'),


# -----------------purchase urls ---------------------------------
    path('purchase/purchaselist/', views.purchase_list, name='purchaselist'),
    path('purchase/purchasedetails/<int:pk>', views.purchase_details, name='purchasedetails'),
    path('purchase/deletepurchase/<int:pk>', views.delete_purchase, name='deletepurchase'),

# -----------------customer urls ---------------------------------
    path('customer/customerlist/', views.customer_list, name='customerlist'),
    path('customer/customerdetails/<int:pk>', views.customer_details, name='customerdetails'),
    path('customer/deletecustomer/<int:pk>', views.delete_customer, name='deletecustomer'),
# -----------------customer urls ---------------------------------
    path('supplier/supplierlist/', views.supplier_list, name='supplierlist'),
    path('supplier/supplierdetails/<int:pk>', views.supplier_details, name='supplierdetails'),
    path('supplier/deletesupplier/<int:pk>', views.delete_supplier, name='deletesupplier'),






]

inventory_management_system/inventory_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/',include('dashboard.urls')),
    path('register/',user_views.register,name="register"),
    path('', auth_views.LoginView.as_view(template_name='user/log/login.html'), name='login'),
    path('logout/', user_views.logout_user, name='logout'),
    path('profile/',user_views.profile_update,name="profile"),
    path('users/userslist',user_views.user_list,name="userlist"),
    path('users/adduser',user_views.add_user,name="adduser"),
    path('users/deleteuser/<int:pk>',user_views.delete_user,name="deleteuser"),
    path('users/edit/<int:pk>',user_views.edit_user,name="edituser"),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT )


inventory_management_system/templates/partials/base.html
{% load static %}

{% if user.is_authenticated %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
<meta name="description" content="POS - Bootstrap Admin Template">
<meta name="keywords" content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern,  html5, responsive">
<meta name="author" content="Dreamguys - Bootstrap Admin Template">
<meta name="robots" content="noindex, nofollow">
<title>{% block title %}{% endblock title %}</title>

<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<link rel="stylesheet" href="{% static 'css/animate.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">

<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">

<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css' %}">

<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {%block script%}

    {%endblock script%}
    
    <div id="global-loader">
    <div class="whirly-loader"> </div>
    </div>

    <div class="main-wrapper">
        {% comment %}  header Section {% endcomment %}
        <div class="header">

        <div class="header-left active">
        <a href="{% url 'dashboard:index' %}" class="logo">
        <img src="{% static 'img/logo.png' %}" alt="">
        </a>
        <a href="{% url 'dashboard:index' %}" class="logo-small">
        <img src="{% static 'img/logo-small.png' %}" alt="">
        </a>
        <a id="toggle_btn" href="javascript:void(0);">
        </a>
        </div>

        <a id="mobile_btn" class="mobile_btn" href="#sidebar">
        <span class="bar-icon">
        <span></span>
        <span></span>
        <span></span>
        </span>
        </a>

        <ul class="nav user-menu">
        <li class="nav-item dropdown has-arrow main-drop">
        <a href="javascript:void(0);" class="dropdown-toggle nav-link userset" data-bs-toggle="dropdown">
        <span class="user-img"><img src="{% static 'img/profiles/avator1.jpg' %}" alt="">
        <span class="status online"></span></span>
        </a>
        <div class="dropdown-menu menu-drop-user">
        <div class="profilename">
        <div class="profileset">
        <span class="user-img"><img src="{% static 'img/profiles/avator1.jpg' %}" alt="">
        <span class="status online"></span></span>
        <div class="profilesets">
        <h6>John Doe</h6>
        <h5>Admin</h5>
        </div>
        </div>
        <hr class="m-0">
        <a class="dropdown-item" href="{% url 'profile' %}"> <i class="me-2" data-feather="user"></i> My Profile</a>
        <a class="dropdown-item" href="generalsettings.html"><i class="me-2" data-feather="settings"></i>Settings</a>
        <hr class="m-0">
        <a class="dropdown-item logout pb-0" href="{% url 'logout' %}"><img src="{% static 'img/icons/log-out.svg' %}" class="me-2" alt="img">Logout</a>
        </div>
        </div>
        </li>
        </ul>

        <div class="dropdown mobile-user-menu">
            <a href="javascript:void(0);" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
            <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="{% url 'profile' %}">My Profile</a>
            <a class="dropdown-item" href="generalsettings.html">Settings</a>
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            </div>
        </div>

        </div>

        {% comment %} Side Bar Section {% endcomment %}
        {% include './sidebar.html' %}
        
        {% comment %} Content Section {% endcomment %}

        <div class="page-wrapper">
        {% block content %} {% endblock content %}
        
        </div>

                
    </div>
        


<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

<script src="{% static 'js/feather.min.js' %}"></script>

<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>

<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/select2/js/select2.min.js' %}"></script>
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'plugins/sweetalert/sweetalert2.all.min.js' %}"></script>
<script src="{% static 'plugins/sweetalert/sweetalerts.min.js' %}"></script>


<script src="{% static 'plugins/apexchart/apexcharts.min.js' %}"></script>
<script src="{% static 'plugins/apexchart/chart-data.js' %}"></script>
 

<script src="{% static 'js/script.js' %}"></script>


</body>

{% else %}
{% url 'login' %}
{% endif %}

inventory_management_system/templates/partials/error.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}Error{% endblock title %}

{% block content %}

<div class="content">
    <div class="page-header">
    <div class="page-title">
    <h4>Error</h4>
    
    </div>
    </div>
    
    <div class="row" >
    <div class="col-lg-8 col-sm-12">
    <div class="card">
    <div class="card-body">
        <div class="alret alret-danger">
            <h4>{{message}}</h4>
        </div>
        <a onClick="window.history.back()" class="btn btn-cancel">Back</a>
    </div>
    </div>
    </div>
    
    </div>
    
</div>


{% endblock content %}

inventory_management_system/templates/partials/nav.html
<nav class="navbar navbar-expand-lg navbar-info bg-info">
    <div class="container">
        <a class="navbar-brand text-white" href={% url 'dashboard:index' %}>KenInventory</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link text-white" href={% url 'dashboard:index' %}>Dashboard <span
                            class="sr-only">(current)</span></a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link text-white" href="profile.html">Admin Profile <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'logout' %}">Logout</a>
                </li>
            </ul>

        </div>
    </div>
</nav>

inventory_management_system/templates/partials/sidebar.html
{% load static %}


{% if user.is_superuser %}

<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
    <div id="sidebar-menu" class="sidebar-menu">
    <ul>

    <li class="active">
    <a href="{% url 'dashboard:index' %}"><img src="{% static 'img/icons/dashboard.svg' %}" alt="img"><span> Dashboard</span> </a>
    </li>

    <li class="submenu">
        <a href="javascript:void(0);"><img src="{% static 'img/icons/product.svg' %}" alt="img"><span> Product</span> <span class="menu-arrow"></span></a>
        <ul>
        <li><a href="{% url 'dashboard:productlist' %}">Product List</a></li>
        <li><a href="{% url 'dashboard:addproduct' %}">Add Product</a></li>
        <li><a href="{% url 'dashboard:categorylist' %}">Category List</a></li>
        <li><a href="{% url 'dashboard:addcategory' %}">Add Category</a></li>
        </ul>
    </li>

    <li class="submenu">
        <a href="javascript:void(0);"><img src="{% static 'img/icons/sales1.svg' %}" alt="img"><span> Sales</span> <span class="menu-arrow"></span></a>
        <ul>
        <li><a href="{% url 'dashboard:salelist' %}">Sales List</a></li>
        <li><a href="{% url 'dashboard:addsale' %}">New Sales</a></li>
        </ul>
    </li>

    <li class="submenu">
        <a href="javascript:void(0);"><img src="{% static 'img/icons/purchase1.svg' %}" alt="img"><span> Purchase</span> <span class="menu-arrow"></span></a>
        <ul>
        <li><a href="{% url 'dashboard:purchaselist' %}">Purchase List</a></li>
        <li><a href="{% url 'dashboard:addpurchase' %}">Add Purchase</a></li>
        </ul>
    </li>

    <li class="submenu">
        <a href="javascript:void(0);"><img src="{% static 'img/icons/users1.svg' %}" alt="img"><span> People</span> <span class="menu-arrow"></span></a>
        <ul>
        <li><a href="{% url 'dashboard:customerlist' %}">Customer List</a></li>
        <li><a href="{% url 'dashboard:addcustomer' %}">Add Customer </a></li>
        <li><a href="{% url 'dashboard:supplierlist' %}">Supplier List</a></li>
        <li><a href="{% url 'dashboard:addsupplier' %}">Add Supplier </a></li>  
        </ul>
    </li>

    <li class="submenu">
        <a href="javascript:void(0);"><img src="{% static 'img/icons/users1.svg' %}" alt="img"><span> Users</span> <span class="menu-arrow"></span></a>
        <ul>
        <li><a href="{% url 'adduser' %}">New User </a></li>
        <li><a href="{% url 'userlist' %}">Users List</a></li>
        </ul>
    </li>

   
    </ul>
    </div>
    </div>
</div>

{% else %}
{% for group in request.user.groups.all %}
    {% if group.name == 'vendors' %}
    <div class="sidebar" id="sidebar">
        <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
        <ul>
    
        <li class="active">
        <a href="{% url 'dashboard:index' %}"><img src="{% static 'img/icons/dashboard.svg' %}" alt="img"><span> Dashboard</span> </a>
        </li>
    
        <li class="submenu">
            <a href="javascript:void(0);"><img src="{% static 'img/icons/product.svg' %}" alt="img"><span> Product</span> <span class="menu-arrow"></span></a>
            <ul>
            <li><a href="{% url 'dashboard:productlist' %}">Product List</a></li>
            <li><a href="{% url 'dashboard:categorylist' %}">Category List</a></li>
            </ul>
        </li>
    
        <li class="submenu">
            <a href="javascript:void(0);"><img src="{% static 'img/icons/sales1.svg' %}" alt="img"><span> Sales</span> <span class="menu-arrow"></span></a>
            <ul>
            <li><a href="{% url 'dashboard:salelist' %}">Sales List</a></li>
            <li><a href="{% url 'dashboard:addsale' %}">New Sales</a></li>
            </ul>
        </li>
    

        <li class="submenu">
            <a href="javascript:void(0);"><img src="{% static 'img/icons/users1.svg' %}" alt="img"><span> People</span> <span class="menu-arrow"></span></a>
            <ul>
            <li><a href="{% url 'dashboard:customerlist' %}">Customer List</a></li>
            <li><a href="{% url 'dashboard:addcustomer' %}">Add Customer </a></li>  
            </ul>
        </li>
    
        
        
        </ul>
        </div>
        </div>
    </div>
    {% elif group.name == 'buyers' %}
    <div class="sidebar" id="sidebar">
        <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
        <ul>
    
        <li class="active">
        <a href="{% url 'dashboard:index' %}"><img src="{% static 'img/icons/dashboard.svg' %}" alt="img"><span> Dashboard</span> </a>
        </li>
    
        <li class="submenu">
            <a href="javascript:void(0);"><img src="{% static 'img/icons/product.svg' %}" alt="img"><span> Product</span> <span class="menu-arrow"></span></a>
            <ul>
            <li><a href="{% url 'dashboard:productlist' %}">Product List</a></li>
            <li><a href="{% url 'dashboard:addproduct' %}">Add Product</a></li>
            <li><a href="{% url 'dashboard:categorylist' %}">Category List</a></li>
            <li><a href="{% url 'dashboard:addcategory' %}">Add Category</a></li>
            </ul>
        </li>
    
    
        <li class="submenu">
            <a href="javascript:void(0);"><img src="{% static 'img/icons/purchase1.svg' %}" alt="img"><span> Purchase</span> <span class="menu-arrow"></span></a>
            <ul>
            <li><a href="{% url 'dashboard:purchaselist' %}">Purchase List</a></li>
            <li><a href="{% url 'dashboard:addpurchase' %}">Add Purchase</a></li>
            </ul>
        </li>
    
        <li class="submenu">
            <a href="javascript:void(0);"><img src="{% static 'img/icons/users1.svg' %}" alt="img"><span> People</span> <span class="menu-arrow"></span></a>
            <ul>
            
            <li><a href="{% url 'dashboard:supplierlist' %}">Supplier List</a></li>
            <li><a href="{% url 'dashboard:addsupplier' %}">Add Supplier </a></li>  
            </ul>
        </li>
    
       
    
       
        </ul>
        </div>
        </div>
    </div>
    {% endif %}
{% endfor %}
{% endif %}

<li class="submenu">
    <a href="javascript:void(0);"><img src="{% static 'img/icons/settings.svg' %}" alt="img"><span> Settings</span> <span class="menu-arrow"></span></a>
    <ul>
    <li><a href="grouppermissions.html">Group Permissions</a></li>
    </ul>
</li>

inventory_management_system/templates/partials/topnav.html
<!--Topside-->
<div class="container">
    <div class="row mt-4">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    Information
                </div>
                <div class="card-body">
                    <marquee behavior="" direction="">
                        <h3 class="my-4">This is the Information</h3>
                    </marquee>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-info text-white">
                    Statistics
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <a class="text-decoration-none text-dark" href="{% url 'dashboard:staff' %}">
                                <div class="card my-card shadow text-center p-3">
                                    <h4>Staff <i class="fas fa-users"></i></h4>
                                    <h3>4</h3>
                                </div>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <a class="text-decoration-none text-dark" href="{% url 'dashboard:product' %}">
                                <div class="card my-card shadow text-center p-3">
                                    <h4>Products <i class="fas fa-box"></i></h4>
                                    <h3>4</h3>
                                </div>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <a class="text-decoration-none text-dark" href="{% url 'dashboard:order' %}">
                                <div class="card my-card shadow text-center p-3">
                                    <h4>Orders <i class="fas fa-shipping-fast"></i></h4>
                                    <h3>4</h3>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End Topside-->